name: Move Project Items Automatically by Labels

on:
  issues:
    types: [labeled]
  pull_request:
    types: [labeled]

jobs:
  move-item:
    runs-on: ubuntu-latest

    permissions:
      issues: write
      pull-requests: write
      project: write
      contents: read

    steps:
      - name: Move "To do"
        if: contains(github.event.label.name, 'todo')
        uses: actions/github-script@v7
        with:
          script: |
            const projectId = 'PVT_kwDODkssLc4BGQkj'; // tu Project ID
            const column = "To do";

            await github.projects.moveProjectItem({
              project_id: projectId,
              column_name: column,
              content_url: github.event.issue?.url || github.event.pull_request.url
            });

      - name: Move "In Progress"
        if: contains(github.event.label.name, 'in-progress')
        uses: actions/github-script@v7
        with:
          script: |
            const projectId = 'PVT_kwDODkssLc4BGQkj';
            const column = "In Progress";

            await github.projects.moveProjectItem({
              project_id: projectId,
              column_name: column,
              content_url: github.event.issue?.url || github.event.pull_request.url
            });

      - name: Move "Review"
        if: contains(github.event.label.name, 'review')
        uses: actions/github-script@v7
        with:
          script: |
            const projectId = 'PVT_kwDODkssLc4BGQkj';
            const column = "Review";

            await github.projects.moveProjectItem({
              project_id: projectId,
              column_name: column,
              content_url: github.event.issue?.url || github.event.pull_request.url
            });

      - name: Move "Done"
        if: contains(github.event.label.name, 'done')
        uses: actions/github-script@v7
        with:
          script: |
            const projectId = 'PVT_kwDODkssLc4BGQkj';
            const column = "Done";

            await github.projects.moveProjectItem({
              project_id: projectId,
              column_name: column,
              content_url: github.event.issue?.url || github.event.pull_request.url
            });
